function getUsers() { $.ajax({ type: "GET", url: "./api/get-users.php", dataType: "json", success: function(t) { count = 1; var a = ""; for (i = 0; i < t.length; i++) a += "<tr>", a += "<td>", a += "" + count, a += "</td>", a += "<td>", a += "" + t[i].username, a += "</td>", a += "<td>", a += "" + t[i].contact, a += "</td>", a += "<td>", a += "" + t[i].role, a += "</td>", a += "<td>", a += "" + t[i].email, a += "</td>", a += "<td>", a += "" + t[i].address, a += "</td>", a += "<td>", a += "" + t[i].status, a += "</td>", "inactive" == t[i].status ? (a += "<td>", a += '<button class="btn btn-sm btn-act btn-success" data-id=' + t[i].id + ' title="Make User Active"><i class="fa fa-refresh"></i><button>', a += '<button class="btn btn-sm btn-edit btn-warning" data-id=' + t[i].id + ' title="Edit User"><i class="fa fa-edit"></i><button>', a += "</td>") : (a += "<td>", a += '<button class="btn btn-sm btn-ina btn-danger" data-id=' + t[i].id + ' title="Make User Active"><i class="fa fa-trash"></i><button>', a += '<button class="btn btn-sm btn-edit btn-warning" data-id=' + t[i].id + ' title="Edit User"><i class="fa fa-edit"></i><button>', a += "</td>"), count++;
            $("#users-table").html(a) } }) }
$(document).ready(function() { getUsers(), $(".submitBtn").click(function() { $("#fullnameError").html(""), $("#contactError").html(""), $("#emailError").html(""), $("#addressEror").html(""), $("#passwordError").html(""); var t = $("#fullname").val(),
            a = $("#contact").val(),
            e = $("#email").val(),
            s = $("#address").val(),
            d = $("#password").val(),
            r = !0;
        t || (r = !1, $("#fullnameError").html("please enter fullname")), "" == a && (r = !1, $("#contactError").html("please enter contact number")), "" == e && (r = !1, $("#emailError").html("please enter email")), "" == s && (r = !1, $("#addressEror").html("please enter address")), "" == d && (r = !1, $("#passwordError").html("please enter password")), 1 == r && $.ajax({ type: "POST", url: "./api/add-user.php", data: { name: t, contact: a, email: e, address: s, password: d }, dataType: "json", success: function(t) { 1 === t.status && (alert("User Successfully Added"), getUsers()) } }) }) }), $("body").on("click", ".btn-act", function() { const t = $(this).attr("data-id");
    $.ajax({ url: "./api/delete-retrive-user.php", method: "POST", data: { id: t, retrive: "retrive" }, success: function(t) { 1 === t.status && getUsers() } }) }), $("body").on("click", ".btn-ina", function() { const t = $(this).attr("data-id");
    $.ajax({ url: "./api/delete-retrive-user.php", method: "POST", data: { id: t }, success: function(t) { 1 === t.status && getUsers() } }) }), $("body").on("click", ".btn-edit", function() { const t = $(this).attr("data-id");
    $.ajax({ type: "GET", url: "./api/get-user-by-id.php", data: { userid: t }, dataType: "json", success: function(t) { console.log(t), $("#ufullname").val(t[0].username), $("#ucontact").val(t[0].contact), $("#uemail").val(t[0].email), $("#upassword").val(t[0].password), $("#uaddress").val(t[0].address), $(".updateBtn").attr("data-id", t[0].id), $("#updateUserModal").modal("show") } }) }), $(".updateBtn").click(function() { var t = $(this).attr("data-id"),
        a = $("#ufullname").val(),
        e = $("#ucontact").val(),
        s = $("#uemail").val(),
        d = $("#upassword").val(),
        r = $("#uaddress").val();
    $.ajax({ type: "POST", url: "./api/update-users.php", data: { id: t, ufullname: a, ucontact: e, uemail: s, upassword: d, uaddress: r }, dataType: "json", success: function(t) { alert("User Updated"), getUsers(), $("#updateUserModal").modal("hide") } }) });